#:schema node_modules/wrangler/config-schema.json
name = "cf-remix-blog"
compatibility_date = "2024-10-04"
main = "./build/worker/index.js"
assets = { directory = "./build/client" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true


[vars]
BLOG_SETTINGS = '''
{
  "title": "我的个人博客",
  "description": "分享我的想法和经验",
  "author": "您的名字",
  "postsPerPage": 10,
  "postsJsonUrl": "https://raw.githubusercontent.com/yourusername/your-repo/main/public/posts.json",
  "theme": "default",
  "footerText": "© {year} 我的个人博客. 保留所有权利.",
  "headerLinks": [
    { "text": "首页", "url": "/" },
    { "text": "文章", "url": "/posts" },
    { "text": "关于", "url": "/about" }
  ],
  "contentWidth": 800,
  "primaryColor": "#3b82f6",
  "fontFamily": "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif"
}
'''